export const metadata = {
  title: 'Pizza Next | Dashboard',
  description: 'Generated by Next.js',
}

export default function DashboardProducts({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      Dashboard Header
      <body>{children}</body>
    </html>
  )
}
