import { Header } from "@/shared/components/shared"
import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Pizza Next | Корзина',
    description: 'Generated by Next.js',
  }
  
  export default function CheckoutProducts({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <main
          className="min-h-screen bg-[#F4F1EE]"
        >
            <Header hasCart={false} hasSearch={false} className="border-gray-200" />
            {children}
        </main>
    )
  }